<a href="https://colab.research.google.com/github/Dicta262/AnalystLab-Africa-Internship-Program/blob/main/Data_Pipelines_and_Automation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ETL: Data Pipelines & Automation

## Data Extraction

In [ ]:
import requests
import csv
from datetime import datetime

# Replace with your actual API key
API_KEY = "a754b7e120ad4a65b591ffc5b154547b"

# Cities you want to check
cities = ["Abuja", "Lagos", "Port Harcourt"]

# Create or overwrite CSV file
with open("nigeria_weather.csv", mode="w", newline="") as file:
    writer = csv.writer(file)
    # Write header row
    writer.writerow(["Date", "Time", "City", "Temperature (°C)", "Feels Like (°C)",
                     "Humidity (%)", "Condition", "Wind Speed (m/s)"])

    for city in cities:
        # Build request URL
        url = f"http://api.openweathermap.org/data/2.5/weather?q={city}&appid={API_KEY}&units=metric"
        response = requests.get(url)
        data = response.json()

        # Extract useful info
        temp = data["main"]["temp"]
        feels_like = data["main"]["feels_like"]
        humidity = data["main"]["humidity"]
        description = data["weather"][0]["description"]
        wind_speed = data["wind"]["speed"]

        # Current date and time
        now = datetime.now()
        date_str = now.strftime("%Y-%m-%d")
        time_str = now.strftime("%H:%M:%S")

        # Write row to CSV
        writer.writerow([date_str, time_str, city, temp, feels_like, humidity, description, wind_speed])

print("Weather data saved to nigeria_weather.csv")

Weather data saved to nigeria_weather.csv

In [ ]:
from google.colab import files

files.download('nigeria_weather.csv')

In [ ]:
print("Raw weather data successfully extracted from the API.")

Raw weather data successfully extracted from the API.

## Data Transformation

In [ ]:
# Import Pandas
import pandas as pd

In [ ]:
# Load the weather dataset
weather_df = pd.read_csv("nigeria_weather.csv")

In [ ]:
# Display original data
print("Original Dataset:")
display(weather_df)

Original Dataset:

,Date,Time,City,Temperature (°C),Feels Like (°C),Humidity (%),Condition,Wind Speed (m/s)
0,2026-06-23,10:36:44,Abuja,28.84,31.06,62,broken clouds,2.54
1,2026-06-23,10:36:45,Lagos,30.44,33.69,60,broken clouds,2.88
2,2026-06-23,10:36:45,Port Harcourt,29.22,32.27,65,light rain,1.04

In [ ]:
# Rename columns
weather_df = weather_df.rename(columns={
    "Temperature (°C)": "Temperature_C",
    "Feels Like (°C)": "Feels_Like_C",
    "Humidity (%)": "Humidity_Percent",
    "Wind Speed (m/s)": "Wind_Speed"
})

In [ ]:
# Convert data types
weather_df["Temperature_C"] = weather_df["Temperature_C"].astype(float)
weather_df["Feels_Like_C"] = weather_df["Feels_Like_C"].astype(float)
weather_df["Humidity_Percent"] = weather_df["Humidity_Percent"].astype(int)
weather_df["Wind_Speed"] = weather_df["Wind_Speed"].astype(float)

In [ ]:
# Check for missing values
print("\nMissing Values:")
print(weather_df.isnull().sum())

Missing Values:
Date                0
Time                0
City                0
Temperature_C       0
Feels_Like_C        0
Humidity_Percent    0
Condition           0
Wind_Speed          0
dtype: int64

In [ ]:
# Display cleaned dataset
print("\nCleaned and Transformed Dataset:")
display(weather_df)

Cleaned and Transformed Dataset:

,Date,Time,City,Temperature_C,Feels_Like_C,Humidity_Percent,Condition,Wind_Speed
0,2026-06-23,10:36:44,Abuja,28.84,31.06,62,broken clouds,2.54
1,2026-06-23,10:36:45,Lagos,30.44,33.69,60,broken clouds,2.88
2,2026-06-23,10:36:45,Port Harcourt,29.22,32.27,65,light rain,1.04

In [ ]:
print("Cleaned and transformed the weather dataset.")

Cleaned and transformed the weather dataset.

In [ ]:
# Save cleaned dataset as Excel

weather_df.to_excel("Cleaned_Weather_Dataset.xlsx", index=False)

print("Excel file saved successfully.")

Excel file saved successfully.

In [ ]:
# Check rows and columns

print("Number of Rows and Columns:")
print(weather_df.shape)

print("\nColumn Names:")
print(weather_df.columns)

display(weather_df)

Number of Rows and Columns:
(3, 8)

Column Names:
Index(['Date', 'Time', 'City', 'Temperature_C', 'Feels_Like_C',
       'Humidity_Percent', 'Condition', 'Wind_Speed'],
      dtype='object')

,Date,Time,City,Temperature_C,Feels_Like_C,Humidity_Percent,Condition,Wind_Speed
0,2026-06-23,10:36:44,Abuja,28.84,31.06,62,broken clouds,2.54
1,2026-06-23,10:36:45,Lagos,30.44,33.69,60,broken clouds,2.88
2,2026-06-23,10:36:45,Port Harcourt,29.22,32.27,65,light rain,1.04

In [ ]:
print("Cleaned Dataset Preview")
weather_df.head()

Cleaned Dataset Preview

,Date,Time,City,Temperature_C,Feels_Like_C,Humidity_Percent,Condition,Wind_Speed
0,2026-06-23,10:36:44,Abuja,28.84,31.06,62,broken clouds,2.54
1,2026-06-23,10:36:45,Lagos,30.44,33.69,60,broken clouds,2.88
2,2026-06-23,10:36:45,Port Harcourt,29.22,32.27,65,light rain,1.04

In [ ]:
from google.colab import files

files.download("Cleaned_Weather_Dataset.xlsx")

## Data Loading

In [ ]:
weather_df.to_csv("processed_weather_data.csv", index=False)

In [ ]:
print("Processed weather data saved successfully.")

Processed weather data saved successfully.

## Basic Analysis

In [ ]:
# Compare temperatures across cities

print("Temperature Comparison Across Cities")
display(weather_df[["City", "Temperature_C"]])

Temperature Comparison Across Cities

            City  Temperature_C
0          Abuja          28.84
1          Lagos          30.44
2  Port Harcourt          29.22

In [ ]:
# Find city with highest humidity

highest_humidity_city = weather_df.loc[
    weather_df["Humidity_Percent"].idxmax(),
    ["City", "Humidity_Percent"]
]

print("\nCity with Highest Humidity:")
print(f"{highest_humidity_city['City']} "
      f"({highest_humidity_city['Humidity_Percent']}%)")

City with Highest Humidity:
Port Harcourt (65%)

In [ ]:
# Compare weather conditions

print("\nWeather Conditions by City")
display(weather_df[["City", "Condition"]])

Weather Conditions by City

            City      Condition
0          Abuja  broken clouds
1          Lagos  broken clouds
2  Port Harcourt     light rain

In [ ]:
# Summary of findings

highest_temp_city = weather_df.loc[
    weather_df["Temperature_C"].idxmax(),
    ["City", "Temperature_C"]
]

print("\nSUMMARY OF FINDINGS")
print(f"• {highest_temp_city['City']} recorded the highest temperature "
      f"at {highest_temp_city['Temperature_C']}°C.")

print(f"• {highest_humidity_city['City']} recorded the highest humidity "
      f"at {highest_humidity_city['Humidity_Percent']}%.")

print("• Weather conditions varied across the selected cities.")

SUMMARY OF FINDINGS
• Lagos recorded the highest temperature at 30.44°C.
• Port Harcourt recorded the highest humidity at 65%.
• Weather conditions varied across the selected cities.

## Brief Report

Weather data was collected from the OpenWeatherMap API for Abuja, Lagos, and Port Harcourt. The dataset was transformed using Pandas by renaming columns, validating data types, and checking for missing values. The cleaned dataset was then stored as a CSV file for future analysis. Basic analysis was performed to compare temperatures, humidity levels, and weather conditions across the selected cities. The results identified the city with the highest temperature and humidity, while also highlighting differences in weather conditions among the cities. This demonstrates a simple ETL (Extract, Transform, Load) data pipeline for automated weather data collection and analysis.